POST http://localhost:3003/api/users
Content-Type:application/json

{
    "username": "test",
    "name": "Mark Burmester",
    "password": "test"
}

###
POST http://localhost:3003/api/users
Content-Type:application/json

{
    "username": "hola",
    "name": "pedro",
    "password": "1234"
}


###
GET http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/blogs/69777e6ce7822e44e412ad32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY5NDk1OGE3OTU3ODRkZGZmYWEwN2IzNiIsImlhdCI6MTc2OTQzNzMzMCwiZXhwIjoxNzY5NDQwOTMwfQ.zZBpEFhlgZIpD8hkO9BXfUBqRTx_vwMPRzi6WStfcK0